name: build
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle
            ~/.m2
            ./.gradle
            ./build
            /opt/hostedtoolcache/
          key: the-cache
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew --no-daemon build
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/